defmodule Bumblebee.Multimodal.Mistral3Test do
  use ExUnit.Case, async: true

  import Bumblebee.TestHelpers

  @moduletag model_test_tags()

  test ":for_conditional_generation" do
    assert {:ok, %{model: model, params: params, spec: spec}} =
             Bumblebee.load_model(
               {:local, "test/fixtures/models/tiny-random-Mistral3ForConditionalGeneration"}
             )

    assert %Bumblebee.Multimodal.Mistral3{architecture: :for_conditional_generation} = spec

    inputs = %{
      "pixel_values" => Nx.broadcast(0.5, {1, 224, 224, 3}),
      "input_ids" => Nx.tensor([[1, 10, 20, 30, 40]]),
      "attention_mask" => Nx.tensor([[1, 1, 1, 1, 1]])
    }

    outputs = Axon.predict(model, params, inputs)

    # Check that we get logits output
    assert Map.has_key?(outputs, :logits)
    assert Nx.shape(outputs.logits) == {1, 5, 1024}

    # Expected values from Bumblebee inference with model generated by:
    # test/fixtures/scripts/generate_expected_values.py (torch.manual_seed(42))
    assert_all_close(
      outputs.logits[[.., 1..3, 1..3]],
      Nx.tensor([
        [
          [3.5014779567718506, -3.962040662765503, -4.744167327880859],
          [2.9522743225097656, -1.380441427230835, -0.4264064133167267],
          [-0.6421813368797302, 4.002349376678467, 7.837586879730225]
        ]
      ]),
      atol: 1.0e-4
    )
  end

  # Test that module structure and options are correct
  test "module structure" do
    assert Bumblebee.Multimodal.Mistral3.architectures() == [:for_conditional_generation]

    # Test default configuration
    spec = %Bumblebee.Multimodal.Mistral3{}
    assert spec.architecture == :for_conditional_generation
    assert spec.image_token_index == 10
    assert spec.spatial_merge_size == 2
    assert spec.projector_hidden_act == :gelu
    assert spec.vision_feature_layer == -1
    assert spec.text_spec == nil
    assert spec.vision_spec == nil
  end

  test "configuration" do
    spec = %Bumblebee.Multimodal.Mistral3{}

    configured =
      Bumblebee.Multimodal.Mistral3.config(spec,
        image_token_index: 5,
        spatial_merge_size: 4
      )

    assert configured.image_token_index == 5
    assert configured.spatial_merge_size == 4
  end

  test "composing text and vision specs" do
    text_spec = %Bumblebee.Text.Mistral3{
      architecture: :for_causal_language_modeling,
      vocab_size: 1024,
      hidden_size: 64
    }

    vision_spec = %Bumblebee.Vision.Pixtral{
      architecture: :base,
      image_size: 224,
      patch_size: 14,
      hidden_size: 64
    }

    spec = %Bumblebee.Multimodal.Mistral3{}

    configured =
      Bumblebee.Multimodal.Mistral3.config(spec,
        text_spec: text_spec,
        vision_spec: vision_spec
      )

    assert configured.text_spec == text_spec
    assert configured.vision_spec == vision_spec
    assert configured.text_spec.vocab_size == 1024
    assert configured.vision_spec.image_size == 224
  end
end
